# Generated by Django 6.1 on 2026-09-10 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre Exacto')),
                ('correo', models.EmailField(default='profesor@institucion.cl', max_length=254)),
                ('token', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(default='Sin Programa', max_length=150)),
                ('cantidad', models.IntegerField(default=0, verbose_name='Horas/Cantidad')),
                ('estado', models.CharField(max_length=50)),
                ('pago_profesores', models.IntegerField(default=0)),
                ('ventas_totales', models.IntegerField(default=0)),
                ('cantidad_respuestas', models.IntegerField(default=0)),
                ('isn', models.IntegerField(default=0)),
                ('nps', models.IntegerField(default=0)),
                ('resultado', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.profesor')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
